### ISSUE TITLE
Searching database can fail with "PHP Warning:  preg_match(): Compilation failed" error

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/db-command#54]
See:

```
wp_options:option_value
PHP Warning:  preg_match(): Compilation failed: number too big in {} quantifier at offset 9 in /Users/danielbachhuber/wp-cli/vendor/wp-cli/php-cli-tools/lib/cli/cli.php on line 234
```

This is easily reproducible on any WordPress install with: `wp db search 'wordpress'

**Comment by gitlost** [comment]
This is due to the 65535 limit on quantifiers in PCRE ([regexp.reference.repetition](http://php.net/manual/en/regexp.reference.repetition.php)), used by `safe_substr()` in  `php-cli-tools`, which limits the size of strings it can deal with properly (though it should fall through to `mb_substr()` to give an approximate answer).

Tried nesting quantifiers (eg `(?:\X{65535}){123}`) but this fails with "regular expression is too large" for offsets > ~240MB due to PCRE expanding out grouped expressions.

So abandoned using quantifiers and have fix using the slower `preg_split(/(\X)/u)` method. Will do a PR in `php-cli-tools` soon.

Will also do a PR suggesting that `intl` be added to the recommended PHP extensions (X > 100 times faster, less memory etc).
